version: '3.5'
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    hostname: homer
    restart: unless-stopped
    volumes:
      - ../Data/assets:/www/assets
      - ../Config/config.yml:/www/assets/config.yml
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.homer.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.homer.entrypoints=web-secure"
      - "traefik.http.routers.homer.middlewares=default-headers@file"
      - "traefik.http.routers.homer.service=homer"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8080" # Proxied Port
